### ISSUE TITLE
Segfaults on PHP 5.3/5.4

### ISSUE THREAD

**Issue by kasperg** [php-vcr/php-vcr#152]
I have a project, wsdl2phpgenerator, which uses php-vcr. First of all: Thanks a bunch for your work!

Second: Our test suite has been [segfaulting on Travis when combining PHP 5.3/5.4 and the latest version of our dependencies](https://travis-ci.org/wsdl2phpgenerator/wsdl2phpgenerator/builds/107964399). Lowest versions have been running fine.

I have tried to narrow down the problem and I believe it to be introduced in php-vcr 1.2.8. [Setting 1.2.7 as the an upper bound to our dependency fixes our build](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/pull/266). Checking [the diff between 1.2.7 and 1.2.8](https://github.com/php-vcr/php-vcr/compare/1.2.7...1.2.8) did not give me any clues regarding the cause of this.

Since PHP 5.3. and 5.4 are both EOL the quickest way to fix the situation would be to bump the required 5.* version to 5.5.

**Comment by buduchail** [comment]
Hi @kasperg, 

wsdl2phpgenerator is a great project, and is the tool we are using in what I describe in issue #153.

We were having the exact same problem as you mention, a build with tests that used php-vcr to provide fixtures for code generated with wsdl2phpgenerator was failing because php was segfaulting when running the tests.

After investigating the issue, I found an easy solution that seems to have fixed the problem on our side. It's in commit f8a40c3.

Could you try running your test suite with my fork and check if the segfaults go away?

**Comment by renatomefidf** [comment]
@kasperg could you please test @buduchail solution?

@buduchail thanks for checking on that, I left some comments in your PR!

**Comment by kasperg** [comment]
@renatomefidf I just tried it and can confirm that [the change fixes this issue](https://travis-ci.org/wsdl2phpgenerator/wsdl2phpgenerator/builds/168510033).

**Comment by renatomefi** [comment]
Thanks for everyone involved here.

This issue is from now fixed on php-vcr 1.3.1: https://github.com/php-vcr/php-vcr/releases/tag/1.3.1
