### ISSUE TITLE
Modernize PHP-VCR?

### ISSUE THREAD

**Issue by moufmouf** [php-vcr/php-vcr#256]
Hey @renatomefi ,

I've submitted a few PRs and plan to submit a few others next week.
One thing I noticed is that the application would probably gain from being strictly typed.

Here is an example:

https://github.com/php-vcr/php-vcr/blob/378033762ca95e89d9f371c2ae3a58e1e2b030db/src/VCR/Util/HttpClient.php#L35

`HttpUtil::parseResponse` expects a string as parameter, but `curl_exec` can return string|false.
In case of error, `HttpUtil::parseResponse` will get "false" and behave erratically.

This kind of problems can be detected automatically by static analysis tools (namely, PHPStan configured in level 7). To be efficient, PHPStan needs typed code.

In parallel, we can see that PHP-VCR still supports PHP 5.3 (!). PHP 5.6 and PHP 7.0 will not be supported anymore in 2 months.

I'm willing to work on a PR to modernize PHP-VCR, but since this would take some time, I thought I would ask you what you think about it first. Here is my battle plan:

- Create a 1.5 branch.
- In composer.json, upgrade PHP-VCR to support PHP >= 7.2.
- Why 7.2? Because it is the only version that supports [parameter type widening](https://wiki.php.net/rfc/parameter-no-type-variance). Parameter type widening allows adding scalar types on parameters while not breaking compatibility with users who would have extended PHP-VCR classes.
- Add scalar types everywhere
- Add PHPStan in CI builds, and fix errors detected by PHPStan

In case you are wondering: it is ok to bump PHP minimum requirement in a minor version. For users with PHP < 7.2, a "composer update" will keep the PHP-VCR dependency to the latest compatible release. Only users with PHP>=7.2 will be able to upgrade to PHP-VCR 1.5+. [Doctrine did this last year](https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html).

Would you agree to merge such a PR if I work on it?

**Comment by moufmouf** [comment]
Ping @renatomefi ,

Sorry to bother you but I have a bit of time right now to work on this and I might not have that time in the coming weeks. Can I start  working on this? Would you merge such a PR?

**Comment by renatomefi** [comment]
Hello @moufmouf!

Wow, thanks a lot for willing to put all this effort!

Currently my only goal in the project was to keep it stable and compatible, I do understand the whole quality this approach can bring to the tool and it's really great!

I'm just unsure whether we'd do that as a 1.5 branch, I think it's safer to go for v2 but then the adoption will be harder, even tho I understand you want to keep the compatibility I think it might be a bit risky since we cannot trust all tests in the project currently!
But nonetheless it's worth to give it a try!

Tell me if you feel safe to go for 1.5 or if 2.0 is better thus I can create the branch!

Also I'd have to first merge some of the PRs with the bug fixes you worked on.

For the new code I'd kindly ask you to try to adhere to atomic commits, thus making it easy to spot any incompatibility post merge, also writing tests for everything which is touched and not tested yet!

What do you think about it?

**Comment by moufmouf** [comment]
Hey @renatomefi !

Excellent!

> Tell me if you feel safe to go for 1.5 or if 2.0 is better thus I can create the branch!

Well, I have no strong opinion on this.

I have no plans for introducing breaking changes, so going to 1.5 seemed more natural.

On the other end, PHP-VCR is a "dev" dependency, and not many libraries depend on it (it is mostly used in projects). For project owners, upgrading will be simple, as long as they do not depend on a library that itself depend on PHP-VCR.
And it might allow us to make more drastic changes to the code without fearing to break something.
So in the end, I'm ok for a v2 as well.

Maybe I can start working on that next version and we can decide later which number to tag based on the changes I made? (I'm really fine with both solutions)

> Also I'd have to first merge some of the PRs with the bug fixes you worked on.

:+1:

> For the new code I'd kindly ask you to try to adhere to atomic commits, thus making it easy to spot any incompatibility post merge, also writing tests for everything which is touched and not tested yet!

With pleasure. I'll work with atomic commits as much as I can and I'll keep an eye on code coverage.
I might also add a few integration tests with cURL.

I'm so happy to have the opportunity to modernize this code base :)

**Comment by JeroenVanOort** [comment]
Since the PR has been merged to branch `1.5`, it seems right to close this issue now.
