### ISSUE TITLE
How does Version Control works?

### ISSUE THREAD

**Issue by Kocal** [php-vcr/php-vcr#263]
Hey!

Today one of the API we use has added a new JSON field in the response for the exact same request (URL, headers, ...), but the already existing cassette has not been updated.

PHP-VCR should warn us or update the already-existing cassette if the response body is different from the previous cassette - for the exact same request - no?

So my question is how does Version Control works? I don't find anything on the website nor in the issues. Is it really implemented? 
One of my colleague recommended me PHP-VCR for this killer feature, but... it doesn't work :man_shrugging: 
 
If it help, I'm using:
- `php-vcr/php-vcr` 1.4.4
- `php-vcr/phpunit-testlistener-vcr` 3.2.1
- PHP 7.2
- PHPUnit 7.4.4

![selection_314](https://user-images.githubusercontent.com/2103975/49595006-63777e00-f977-11e8-9bf3-7376fa244572.png)
> http://php-vcr.github.io/#page-nav-Features

Thanks!

**Comment by renatomefi** [comment]
Hello @Kocal 

The version control is git itself, when you first run and the cassette is recorded it'll be in your file which then can be committed, if you remove it and make a new call you can commit the new version, so on and so forth!

Is that more clear or you need more details?

**Comment by Kocal** [comment]
Ah, okay.
So it means that:
- I should be aware of API response's changes changes
- If I should update every cassettes, the best thing to do is to remove every of my cassettes and run PHPUnit again? 

And so, what about `See if external APIs change` on the slide? 🤔

**Comment by Kocal** [comment]
Sorry to ping you @renatomefi, but I don't think you saw my last message.
Thanks!

**Comment by tristanbes** [comment]
I'm also interested in this

**Comment by JeroenVanOort** [comment]
I'm answering this not because I think the answer will be of use to @Kocal (it's been a while) but more as a general explanation for anyone having the same question.

So, there are two conflicting interests at play here. The first is that you want to be alerted of any changes in an API you're consuming. And the other one is that, for many reasons, you don't always want to test against a live API (e.g. not being able to call the API from your CI, responses not being consistent, etc). PHP-VCR can do many things, but not satisfy both demands at the same time. If not for making live calls, how else would so discover an API change?

PHP-VCR only makes sure responses can be cached and not much else. However, one can still detect changes on API's by using the recordings. This is how I do that:

1. Write your test, run it and commit the resulting recording in your VCS (like git).
2. When you want to check if the API has changed, remove the recording, run the test again and review what has changes in the recording.

That's 'version control of recordings'. Sadly, no magic solution to this problem has been found.
